# 印刷PDF用設定ファイル
# 元々の設定ファイルから項目を継承する
inherit: ["config.yml"]

# 横書き
direction: "ltr"

# 印刷所の名前を設定する
prt: 自宅のプリンタ

# 表紙を作る
cover: cover.xhtml

# 裏表紙を作る
backcover: backcover.xhtml

# 大扉は作らない
titlepage: false

# 奥付は作らない
# colophon: colophon.xhtml

# 著者紹介は自作したXMTMLファイルを使う
# profile: profile.xhtml
# profiletitle: 著者紹介

# 目次の章立ての部分にリンクを作らない
chapterlink: null

# 外部リンクを無効にする
externallink: false